image: alpine:latest

stages:
  - build
  - test
  - deploy

build_frontend:
  stage: build
  script:
    - echo "Build Frontend OK"

build_backend:
  stage: build
  script:
    - echo "Build Backend OK"

test_backend:
  stage: test
  script:
    - echo "Tests Backend OK"

deploy_k8s:
  stage: deploy
  script:
    - echo "Deploy Kubernetes OK (simulated)"
