stages:
  - build
  - test
  - deploy

build_frontend:
  stage: build
  script:
    - echo "✅ Build Front-end simulated"

build_backend:
  stage: build
  script:
    - echo "✅ Build Back-end simulated"

test_backend:
  stage: test
  script:
    - echo "✅ Test Back-end simulated"

deploy_k8s:
  stage: deploy
  script:
    - echo "✅ Deploy Kubernetes skipped (no cluster)"
  only:
    - main

